// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 2
		case r == 32: // [' ',' ']
			return 1
		case 65 <= r && r <= 90: // ['A','Z']
			return 3
		case r == 95: // ['_','_']
			return 4
		case 97 <= r && r <= 122: // ['a','z']
			return 3
		case r == 243: // [\u00f3,\u00f3]
			return 3
		case r == 261: // [\u0105,\u0105]
			return 3
		case r == 263: // [\u0107,\u0107]
			return 3
		case r == 281: // [\u0119,\u0119]
			return 3
		case r == 322: // [\u0142,\u0142]
			return 3
		case r == 324: // [\u0144,\u0144]
			return 3
		case r == 347: // [\u015b,\u015b]
			return 3
		case r == 378: // [\u017a,\u017a]
			return 3
		case r == 380: // [\u017c,\u017c]
			return 3
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		case r == 243: // [\u00f3,\u00f3]
			return 6
		case r == 261: // [\u0105,\u0105]
			return 6
		case r == 263: // [\u0107,\u0107]
			return 6
		case r == 281: // [\u0119,\u0119]
			return 6
		case r == 322: // [\u0142,\u0142]
			return 6
		case r == 324: // [\u0144,\u0144]
			return 6
		case r == 347: // [\u015b,\u015b]
			return 6
		case r == 378: // [\u017a,\u017a]
			return 6
		case r == 380: // [\u017c,\u017c]
			return 6
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		case r == 243: // [\u00f3,\u00f3]
			return 6
		case r == 261: // [\u0105,\u0105]
			return 6
		case r == 263: // [\u0107,\u0107]
			return 6
		case r == 281: // [\u0119,\u0119]
			return 6
		case r == 322: // [\u0142,\u0142]
			return 6
		case r == 324: // [\u0144,\u0144]
			return 6
		case r == 347: // [\u015b,\u015b]
			return 6
		case r == 378: // [\u017a,\u017a]
			return 6
		case r == 380: // [\u017c,\u017c]
			return 6
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		case r == 243: // [\u00f3,\u00f3]
			return 6
		case r == 261: // [\u0105,\u0105]
			return 6
		case r == 263: // [\u0107,\u0107]
			return 6
		case r == 281: // [\u0119,\u0119]
			return 6
		case r == 322: // [\u0142,\u0142]
			return 6
		case r == 324: // [\u0144,\u0144]
			return 6
		case r == 347: // [\u015b,\u015b]
			return 6
		case r == 378: // [\u017a,\u017a]
			return 6
		case r == 380: // [\u017c,\u017c]
			return 6
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		case r == 243: // [\u00f3,\u00f3]
			return 6
		case r == 261: // [\u0105,\u0105]
			return 6
		case r == 263: // [\u0107,\u0107]
			return 6
		case r == 281: // [\u0119,\u0119]
			return 6
		case r == 322: // [\u0142,\u0142]
			return 6
		case r == 324: // [\u0144,\u0144]
			return 6
		case r == 347: // [\u015b,\u015b]
			return 6
		case r == 378: // [\u017a,\u017a]
			return 6
		case r == 380: // [\u017c,\u017c]
			return 6
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 5
		case 65 <= r && r <= 90: // ['A','Z']
			return 6
		case r == 95: // ['_','_']
			return 7
		case 97 <= r && r <= 122: // ['a','z']
			return 6
		case r == 243: // [\u00f3,\u00f3]
			return 6
		case r == 261: // [\u0105,\u0105]
			return 6
		case r == 263: // [\u0107,\u0107]
			return 6
		case r == 281: // [\u0119,\u0119]
			return 6
		case r == 322: // [\u0142,\u0142]
			return 6
		case r == 324: // [\u0144,\u0144]
			return 6
		case r == 347: // [\u015b,\u015b]
			return 6
		case r == 378: // [\u017a,\u017a]
			return 6
		case r == 380: // [\u017c,\u017c]
			return 6
		}
		return NoState
	},
}
