// Code generated by gocc; DO NOT EDIT.

package parser

const numNTSymbols = 3

type (
	gotoTable [numStates]gotoRow
	gotoRow   [numNTSymbols]int
)

var gotoTab = gotoTable{
	gotoRow{ // S0
		-1, // S'
		1,  // Declarations
		2,  // Declaration
	},
	gotoRow{ // S1
		-1, // S'
		-1, // Declarations
		4,  // Declaration
	},
	gotoRow{ // S2
		-1, // S'
		-1, // Declarations
		-1, // Declaration
	},
	gotoRow{ // S3
		-1, // S'
		-1, // Declarations
		-1, // Declaration
	},
	gotoRow{ // S4
		-1, // S'
		-1, // Declarations
		-1, // Declaration
	},
}
